# Generated by Django 3.2.22 on 2023-10-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='free_checks',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
